spring:
  datasource:
    url: jdbc:mysql://${DBHOST}:${DBPORT}/${DBDATABASE}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DBUSER}
    password: ${DBPASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect