spring:
  application:
    name: Cadcar
  profiles:
    active: ${PROFILE:prd}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  show-sql: true
  flyway:
    enabled: true
jwt:
  secret: ${JWTSECRET}
  expiration-ms: ${JWTEXPIRATION:3600000}
